# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute3DcrossProductCPP <- function(y, z) {
    .Call(`_moPLOT_compute3DcrossProductCPP`, y, z)
}

computeVectorLengthCPP <- function(vec) {
    .Call(`_moPLOT_computeVectorLengthCPP`, vec)
}

normalizeVectorCPP <- function(vec, prec) {
    .Call(`_moPLOT_normalizeVectorCPP`, vec, prec)
}

normalizeMatrixRowsCPP <- function(mat, prec) {
    .Call(`_moPLOT_normalizeMatrixRowsCPP`, mat, prec)
}

computeAngleCPP <- function(vec1, vec2, prec) {
    .Call(`_moPLOT_computeAngleCPP`, vec1, vec2, prec)
}

findNextCellCPP <- function(gradient) {
    .Call(`_moPLOT_findNextCellCPP`, gradient)
}

convertIndices2CellIDCPP <- function(indices, dims) {
    .Call(`_moPLOT_convertIndices2CellIDCPP`, indices, dims)
}

convertCellID2IndicesCPP <- function(cellID, dims) {
    .Call(`_moPLOT_convertCellID2IndicesCPP`, cellID, dims)
}

getNeighbourhood <- function(d, include_diagonals) {
    .Call(`_moPLOT_getNeighbourhood`, d, include_diagonals)
}

imputeBoundary <- function(moGradMat, gradMatList, dims) {
    .Call(`_moPLOT_imputeBoundary`, moGradMat, gradMatList, dims)
}

getCriticalPointsCellCPP <- function(moGradMat, gradMatList, div, locallyNondominated, dims, sinks_only) {
    .Call(`_moPLOT_getCriticalPointsCellCPP`, moGradMat, gradMatList, div, locallyNondominated, dims, sinks_only)
}

connectedComponentsGrid <- function(ids, dims) {
    .Call(`_moPLOT_connectedComponentsGrid`, ids, dims)
}

integrateVectorField <- function(gradMat, dims, sinks) {
    .Call(`_moPLOT_integrateVectorField`, gradMat, dims, sinks)
}

locallyNondominatedCPP <- function(fnMat, dims, includeDiagonals) {
    .Call(`_moPLOT_locallyNondominatedCPP`, fnMat, dims, includeDiagonals)
}

changeOfSignCPP <- function(fnVec, dims, includeDiagonals) {
    .Call(`_moPLOT_changeOfSignCPP`, fnVec, dims, includeDiagonals)
}

changeOfBasin <- function(basins, dims) {
    .Call(`_moPLOT_changeOfBasin`, basins, dims)
}

gridBasedGradientCPP <- function(fnVec, dims, stepSizes, precNorm, precAngle) {
    .Call(`_moPLOT_gridBasedGradientCPP`, fnVec, dims, stepSizes, precNorm, precAngle)
}

cumulateGradientsCPP <- function(centers, gradients, stopCells, precVectorLength, precNorm, fixDiagonals, cumulateGradientLength) {
    .Call(`_moPLOT_cumulateGradientsCPP`, centers, gradients, stopCells, precVectorLength, precNorm, fixDiagonals, cumulateGradientLength)
}

getBiObjGradientCPP <- function(g1, g2, precNorm, precAngle) {
    .Call(`_moPLOT_getBiObjGradientCPP`, g1, g2, precNorm, precAngle)
}

getTriObjGradientCPP <- function(g1, g2, g3, precNorm, precAngle) {
    .Call(`_moPLOT_getTriObjGradientCPP`, g1, g2, g3, precNorm, precAngle)
}

getBiObjGradientGridCPP <- function(gradMat1, gradMat2, precNorm, precAngle) {
    .Call(`_moPLOT_getBiObjGradientGridCPP`, gradMat1, gradMat2, precNorm, precAngle)
}

getTriObjGradientGridCPP <- function(gradMat1, gradMat2, gradMat3, precNorm, precAngle) {
    .Call(`_moPLOT_getTriObjGradientGridCPP`, gradMat1, gradMat2, gradMat3, precNorm, precAngle)
}

calculateMaxDisplayHeightCPP <- function(heights, dims, includeDiagonals) {
    .Call(`_moPLOT_calculateMaxDisplayHeightCPP`, heights, dims, includeDiagonals)
}

